logging:
  level:
    com:
      javatechie:
        spring:
          auditing:
            api: DEBUG
  file: Log/myLog.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] -%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] [%thread] %-5level %logger{40}-%msg%n'
server:
  port: 8085
spring.profiles: local  
management:
 health:
   status:
     order: FATAL, DOWN, OUT_OF_SERVICE, UNKNOWN, UP
     http-mapping:
       UP: 200  
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auditdb?useSSL=false
    username: root
    password: P@ssw0rd
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: true
    properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: hussain.shahzad250@gmail.com 
    password: XXXXXXXXXXX
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        transport:
          protocol: smtp      
  redis:
    database: 0
    host: localhost
    port: 6379    
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
